[package]
name = "webnis-server"
version = "0.1.0"
authors = ["mikevs <mikevs@xs4all.net>"]
edition = "2018"

[dependencies]
actix = "0.7.9"
actix-web = { version = "0.7.18", features = [ "alpn" ] }
base64 = "0.10.0"
clap = "2.32.0"
env_logger = "0.6.0"
failure = "0.1.5"
failure_derive = "0.1.5"
futures = "0.1.25"
gdbm = "0.1.1"
http = "0.1.15"
ipnet = "2.0.0"
lazy_static = "1.2.0"
libc = "0.2.48"
log = "0.4.6"
net2 = "0.2.33"
openssl = "0.10.16"
percent-encoding = "1.0.1"
pwhash = "0.3.0"
rlua = "0.15"
serde = "1.0.85"
serde_derive = "1.0.85"
serde_json = "1.0.37"
toml = "0.4.10"
